### ISSUE TITLE
Make the Repository a Python package

### ISSUE THREAD

**Issue by yFetz** [dumaalex998/stock_market#1]
1) structure the code into a **package** using a separate folder
2) add an **__init__.py** file
3) modify the **main.py** script in order import the code correclty

**Comment by dumaalex998** [comment]
- solved 1 in: 479c74d2ee91eba7e54b09bd3ab998659e91741c
- solved 2 in: ca376d6d08c023bf8d1447e9410ef2d123a08621
- solved 3 in: 8d91ce9c2a6979f4a539357e33831c1d45cf8dd1
