### ISSUE TITLE
Manage database connection an populate users table from csv

### ISSUE THREAD

**Issue by LeonardoAntinucci** [dumaalex998/stock_market#10]
Hi @yFetz, 
In my last commit (ee85bc8bf122d94d01406832b421d596b7ce14d8) I added a simple database file with the users table.
Could you implement a function that manages the connection?
Also, the table is empty. It would be great to populate it from a CSV file!
Good luck!

**Comment by yFetz** [comment]
closed in 94a58817a5d2141dd0474d3d42eddd9e5daf2031!
