### ISSUE TITLE
We need readable code!

### ISSUE THREAD

**Issue by yFetz** [dumaalex998/stock_market#11]
The code is a little bit messy. Also, many name variables are not meaningful.
I would not add any other line of code until the situation gets better.
Please do something!

**Comment by megmenegazzi** [comment]
Hi @yFetz !
I've finished my work:
- starting from 958fb4e8f8aa1757a1da15d9e477e8ee533ffa2e line codes are under 79 chars
- starting from 0ba904ce0182886e29d7f73407d4476f61614f72 lines are commented
- starting from a2acbe26362f23aba2b2a6b3a048222fcbfd0089 variable names improved
Now you can get to work agaain...
Have fun!
