### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by LeonardoAntinucci** [dumaalex998/stock_market#12]
Docstrings are missing from a lot of functions. In order to have a good documentation (Maybe done with Sphinx: https://www.sphinx-doc.org/en/master/usage/quickstart.html) We need to insert docstrings. 
This guide is a good start (see "Docstring format"): https://stackabuse.com/python-docstrings/

**Comment by yFetz** [comment]
Hi @LeonardoAntinucci !
I updated the project inserting docstrings in the  .py files.
To be more specific:
- Add docstrings in dbmanager.py: cfe6c361c919e4dc743c2f9f6429125703f06969
- Add docstrings in stock.py: fc5d9d3f55709f4d15f593fcd897571dc7ba828f
- Add docstrings in currency_handler.py: bbfd93d674e0b1d0caf7388c99b99c51deb6ef4e
- Add docstrings in main.py (AND CLOSE ISSUE): d9ff8f6ef2fc5dc38d7d85cf406b887e554a3cfc
