### ISSUE TITLE
Create tests for our modules

### ISSUE THREAD

**Issue by yFetz** [dumaalex998/stock_market#13]
We have created many modules for our project. It's never too late to create some tests!
- Add a new folder called "tests" to the project
- Add python module called "tests/test_MODULENAME.py"
- Create the first tests

**Comment by megmenegazzi** [comment]
Hi!
I've created the tests folder and the test_main.py module.
Unfortunately, main.py is not passing the tests! I would create an issue about this.
Closed in 0b61ec07f17e2f974538132eb2e646fd81c5ffdf!
