### ISSUE TITLE
All tests of main.py fail

### ISSUE THREAD

**Issue by dumaalex998** [dumaalex998/stock_market#14]
Hi @LeonardoAntinucci. 
@margheritamenegazzi wrote some tests for main.py but they all fail. Can you improve the situation please? Thank you.

**Comment by LeonardoAntinucci** [comment]
Hi! Now main.py passes all the tests, I created another test that checks the extension of the file.
Closed in fe50308e599b058d95f2f41e45c6e5e5639a8e78!
