### ISSUE TITLE
No tests for currency_handler.py

### ISSUE THREAD

**Issue by LeonardoAntinucci** [dumaalex998/stock_market#15]
There are no tests made for currency_handler.py.
Suggestion:
- check that the price is always >0
- check that the symbol is a string
feel free to add any other tests you may consider useful.

**Comment by megmenegazzi** [comment]
Hi @LeonardoAntinucci !
I created a test module for currency_handler.py accepting the suggestions you gave me.
Closed in 13e64f47b0e607f0a2c05211674f7fdfe179b5a4.
