### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by megmenegazzi** [dumaalex998/stock_market#16]
Reviewing the code I noticed the following:
- Some lines in main.py are exceeding 79 characters
- allowed_currencies.cvs has only 2 currencies available

Can you improve the situation @dumaalex998 ?
Thanks!

**Comment by dumaalex998** [comment]
Hi!
I've fixed the coding style in main.py.
I've also added more currencies in allowed_currencies.csv and solved minor bugs in main.py. Now everything seems to work!
Closed in 71cb204b1ce772a653d9bb3fadf640c372e111bf.
