### ISSUE TITLE
Allowed companies

### ISSUE THREAD

**Issue by dumaalex998** [dumaalex998/stock_market#17]
We need a way to inform the user about the companies' symbols available. A good idea could be to write some of them in a CSV file and make the user choose.

**Comment by LeonardoAntinucci** [comment]
Hi! @dumaalex998 
I've added a new .csv file with the companies (in 983ad8a269e5872181525b51fe48c512117ea82e)
I've also added a new function that reads the data from it (31da8f3963f030e875bee31768f0573fddee117c) and commented it with docstrings.
Closed in 80d44a56ad9b8f0c5611aee525667eeee2b98485.
