### ISSUE TITLE
A script for adding and removing users from the database

### ISSUE THREAD

**Issue by dumaalex998** [dumaalex998/stock_market#18]
In scripts/script.py we have some functions to create the users' table and authenticate the user.  We need other 2 functions to add and remove users.

**Comment by yFetz** [comment]
Hi @dumaalex998.
You can find 2 more functions in the dbmanager.py:
- one that adds users
- one that remove users
Also, I've updated the script. If you run it directly you can populate the db.
Closed in 4d0830a9cf5f7b176334805f33ee428e782a9aa8!
