### ISSUE TITLE
Properly document the code

### ISSUE THREAD

**Issue by LeonardoAntinucci** [dumaalex998/stock_market#2]
1. Document main.py
2. Document stock.py inside python_package

**Comment by yFetz** [comment]
Please @LeonardoAntinucci note that main.py does not need documentation

**Comment by megmenegazzi** [comment]
Solved in 4507a48105ab3defc5f1d200b8cf8eed27a004f0

**Comment by dumaalex998** [comment]
Great guys! Issue can be closed.
