### ISSUE TITLE
Improve README and comment the code

### ISSUE THREAD

**Issue by dumaalex998** [dumaalex998/stock_market#21]
The README is ok but i would like to have it more detailed. We want new users to understand how everything works.
Also, it could be a good idea to comment meaningful portions of the code.

**Comment by yFetz** [comment]
Hello!
I've improved the README (9e14f576c53d06e18dee5af4432de7125392681a) and commented the code of the db manager ant the main.
Closed in 87464f3ca5bb2bf700709cf248cf2470a90262d9.
