### ISSUE TITLE
Add documentation with sphinx

### ISSUE THREAD

**Issue by LeonardoAntinucci** [dumaalex998/stock_market#23]
We do not provide any documentation in our project. Please see how to create one with sphinx!

**Comment by megmenegazzi** [comment]
Documentation with Sphinx added in: be20a92b39cf7b71978a4a6c7437a08313b9e640.
I have also improved the readme with a Documentation section.
Closed in: 33daa912bf364c92dfab81173bca3455a7d6be6f.
