### ISSUE TITLE
Remove constants from main.py and use argparse

### ISSUE THREAD

**Issue by dumaalex998** [dumaalex998/stock_market#5]
1. Use one positional argument. Suggestions: it should be the company label (like "AAPL -> Apple")
2. Use one optional argument. Suggestions: the currency in which the user would like to have the value displayed (Euro, Dollar, GBP)

Let me know if I have to be more precise on that!

**Comment by megmenegazzi** [comment]
Closed part 1 in 9e6137a294d0035c02c36447e084549997ebb3b1

**Comment by megmenegazzi** [comment]
Closed part2 in 9ff8dbe1a5df0511951897ced7569dfd81417ce1

**Comment by dumaalex998** [comment]
Ok that seems to work! Nice!
