### ISSUE TITLE
Use the csv module

### ISSUE THREAD

**Issue by yFetz** [dumaalex998/stock_market#7]
Hello guys,
You could use a csv file to convert the dollar into the currency chosen by the user. It is way more flexible.

**Comment by dumaalex998** [comment]
I've added pandas csv reading.

**Comment by yFetz** [comment]
I suggest you to read the csv and store it in a variable in the main function. It would be more flexible to pass the entire dataframe with the allowed currencies and their value to the various modules.

**Comment by dumaalex998** [comment]
Thanks @yFetz ! 
Solved in 7b531b4688bc00c54dd9ead1a1953008726bfca9
