### ISSUE TITLE
Improve argument parsing

### ISSUE THREAD

**Issue by dumaalex998** [dumaalex998/stock_market#8]
Try to implement a **better argument parsing.** The help messages are not really "helpful".  Also, you can find a lot of information to improve this step in the module documentation: _https://docs.python.org/3/library/argparse.html_
Let me know if you have any doubts!

**Comment by LeonardoAntinucci** [comment]
I have improved help messages, added a version argument and an epilog.
Solved in 0913232009038b61f73b3514598d8e67d5633682
