### ISSUE TITLE
Develop the helper code to create a database

### ISSUE THREAD

**Issue by dumaalex998** [dumaalex998/stock_market#9]
Hi guys! Below you can find the next goals to achieve:
- create a new folder containing a file that manages the db
- create a db

**Comment by LeonardoAntinucci** [comment]
I updated the project and added a new folder with a dbmanager python file. 
First step completed in ca24582f097a23a837206d73a33587bd4a136eb9!

**Comment by LeonardoAntinucci** [comment]
I added users' table!
Below you can find the schema:

![image](https://user-images.githubusercontent.com/57446803/70255698-7c339300-1787-11ea-8eda-4483af57f2fc.png)

Closed in ee85bc8bf122d94d01406832b421d596b7ce14d8!
